# -*- coding: utf-8 -*-
"""For Deployment Solar_Panel_Regression_Group_4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1L9ATSRfbOV1KdRwH0nC6o8o5Cj7Vs-pe
"""

import numpy as np
import pandas as pd
import pickle
from sklearn.ensemble import GradientBoostingRegressor

df = pd.read_csv('solarpowergeneration.csv')

df['average-wind-speed-(period)'] = df['average-wind-speed-(period)'].fillna(df['average-wind-speed-(period)'].mean())

df_features = df.drop(['power-generated'], axis=1)

scaled_df = df_features.copy()
for col in scaled_df.select_dtypes(include=[np.number]).columns:
    mean_val = scaled_df[col].mean()
    std_val = scaled_df[col].std()
    if std_val != 0:
        scaled_df[col] = (scaled_df[col] - mean_val) / std_val
    else:
        scaled_df[col] = 0.0

y = df['power-generated']
x = df_features

x_train = x.iloc[0:2336]

y_train = y.iloc[0:2336]

x_test = x.iloc[2336:2920]

y_test = y.iloc[2336:2920]

x_train.shape, x_test.shape, y_train.shape, y_test.shape

params = {
    'n_estimators': 100,
    'learning_rate': 0.1,
    'max_depth': 3,
    'random_state': 42
}

# Train the model
model = GradientBoostingRegressor(learning_rate= 0.1, max_depth= 3, n_estimators= 100, random_state= 42)
model.fit(x_train, y_train)
# Pickle the trained model (saves the model object with all parameters and trained state)
with open('gradient_boosting_model.pkl', 'wb') as f:
    pickle.dump(model, f)

import streamlit as st

@st.cache_resource
def load_model():
    with open("gradient_boosting_model.pkl", "rb") as f:
        model = pickle.load(f)
    return model

model = load_model()

# --------------------------------------------------------
# PAGE CONFIG
# --------------------------------------------------------
st.set_page_config(page_title="Solar Power Prediction App", layout="wide")

st.title("⚡ Solar Power Generation Prediction")
st.markdown("""
This app uses a **Gradient Boosting Regression Model**  
to predict **solar power generated** based on various meteorological features.
""")

# --------------------------------------------------------
# LOAD MODEL
# --------------------------------------------------------
@st.cache_resource
def load_model():
    with open("gradient_boosting_model.pkl", "rb") as f:
        model = pickle.load(f)
    return model

model = load_model()

# --------------------------------------------------------
# USER INPUT SECTION
# --------------------------------------------------------
st.header("🔧 Enter Feature Values Manually")
st.markdown("Provide values for each feature below to predict power generation.")

# Feature names (modify based on your dataset)
feature_names = [
    'temperature', 
    'humidity', 
    'wind-speed', 
    'irradiance',
    'average-wind-speed-(period)'
]

inputs = {}
for feature in feature_names:
    inputs[feature] = st.number_input(f"{feature}", value=0.0)

# Prediction button
if st.button("Predict"):
    try:
        input_df = pd.DataFrame([inputs])
        prediction = model.predict(input_df)[0]

        st.success("Prediction Successful!")
        st.metric("🔮 Predicted Power Generated", f"{prediction:.2f} units")
    except Exception as e:
        st.error(f"Error: {e}")

# --------------------------------------------------------
# FOOTER
# --------------------------------------------------------
st.markdown("---")
st.markdown("""
### 👨‍💻 Developer Notes
- **X** = Features  
- **y** = Target variable *(power-generated)*  
- Model used: **Gradient Boosting Regressor**  
""")
