# -*- coding: utf-8 -*-
"""For Deployment Solar_Panel_Regression_Group_4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1L9ATSRfbOV1KdRwH0nC6o8o5Cj7Vs-pe
"""

import numpy as np
import pandas as pd
import pickle
from sklearn.ensemble import GradientBoostingRegressor

df = pd.read_csv('solarpowergeneration.csv')

df['average-wind-speed-(period)'] = df['average-wind-speed-(period)'].fillna(df['average-wind-speed-(period)'].mean())

df_features = df.drop(['power-generated'], axis=1)

scaled_df = df_features.copy()
for col in scaled_df.select_dtypes(include=[np.number]).columns:
    mean_val = scaled_df[col].mean()
    std_val = scaled_df[col].std()
    if std_val != 0:
        scaled_df[col] = (scaled_df[col] - mean_val) / std_val
    else:
        scaled_df[col] = 0.0

y = df['power-generated']
x = df_features

y.isnull().sum()

x.isnull().sum()

y.shape, x.shape

2920 * (80/100)

2920-2336

x_train = x.iloc[0:2336]

y_train = y.iloc[0:2336]

x_test = x.iloc[2336:2920]

y_test = y.iloc[2336:2920]

x_train.shape, x_test.shape, y_train.shape, y_test.shape

params = {
    'n_estimators': 100,
    'learning_rate': 0.1,
    'max_depth': 3,
    'random_state': 42
}

# Train the model
model = GradientBoostingRegressor(learning_rate= 0.1, max_depth= 3, n_estimators= 100, random_state= 42)
model.fit(x_train, y_train)
# Pickle the trained model (saves the model object with all parameters and trained state)
with open('gradient_boosting_model.pkl', 'wb') as f:
    pickle.dump(model, f)

import streamlit as st
st.set_page_config(page_title="Solar Power Prediction App", layout="wide")

st.title("⚡ Solar Power Generation Prediction")
st.markdown("""
This app uses a **Gradient Boosting Regression Model**
to predict **solar power generated** based on various meteorological features.
""")

# --------------------------------------------------------
# LOAD MODEL
# --------------------------------------------------------
@st.cache_resource
def load_model():
    with open("gradient_boosting_model.pkl", "rb") as f:
        model = pickle.load(f)
    return model

model = load_model()

# --------------------------------------------------------
# USER INPUT SECTION
# --------------------------------------------------------
st.header("🔧 Enter Feature Values")
st.markdown("Provide values for each feature below to predict power generation.")

uploaded_csv = st.file_uploader("Upload a CSV with feature values (Optional)", type=["csv"])

# If user uploads a CSV, predict for whole file
if uploaded_csv:
    df_input = pd.read_csv(uploaded_csv)
    st.write("### Uploaded Data Preview")
    st.dataframe(df_input.head())

    # Prediction
    try:
        preds = model.predict(df_input)
        df_input["Predicted Power Generated"] = preds
        st.success("Prediction completed!")
        st.write("### 🔮 Predictions")
        st.dataframe(df_input)

        # Download
        csv_download = df_input.to_csv(index=False)
        st.download_button("📥 Download Predictions", data=csv_download,
                           file_name="solar_predictions.csv",
                           mime="text/csv")
    except Exception as e:
        st.error(f"Error: {e}")

else:
    # Manual entry mode
    st.markdown("Or **manually enter feature values** below:")

    # Example feature set (replace with your actual columns)
    feature_names = [
        'temperature', 'humidity', 'wind-speed', 'irradiance',
        'average-wind-speed-(period)'
    ]

    inputs = {}
    for feature in feature_names:
        inputs[feature] = st.number_input(f"{feature}", value=0.0)

    if st.button("Predict"):
        try:
            input_df = pd.DataFrame([inputs])
            prediction = model.predict(input_df)[0]

            st.success("Prediction Successful!")
            st.metric("🔮 Predicted Power Generated", f"{prediction:.2f} units")
        except Exception as e:
            st.error(f"Error: {e}")

# --------------------------------------------------------
# FOOTER
# --------------------------------------------------------
st.markdown("---")
st.markdown("""
### 👨‍💻 Developer Notes
- **X** = features
- **y** = target variable *(power-generated)*
- Model: **Gradient Boosting Regressor**
""")
