# -*- coding: utf-8 -*-
"""Deployment - 2 : Solar Panel Regressionipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17bLumFfkAEKNa-8Qquq9xEbb6GAbk9ha
"""

# -*- coding: utf-8 -*-
import numpy as np
import pandas as pd
import pickle
from sklearn.ensemble import GradientBoostingRegressor

# Load dataset
df = pd.read_csv('solarpowergeneration.csv')

# Handle missing values
df['average-wind-speed-(period)'] = df['average-wind-speed-(period)'].fillna(
    df['average-wind-speed-(period)'].mean()
)

# Separate features and target
df_features = df.drop(['power-generated'], axis=1)
y = df['power-generated']

# ------------------------------
# COMPUTE SCALER VALUES
# ------------------------------
means = df_features.mean()
stds = df_features.std()

# Save scaler
scaler = {
    "means": means.to_dict(),
    "stds": stds.to_dict(),
    "feature_order": list(df_features.columns)
}

with open("scaler.pkl", "wb") as f:
    pickle.dump(scaler, f)

# ------------------------------
# APPLY SCALING
# ------------------------------
scaled_df = (df_features - means) / stds

# Training split
x_train = scaled_df.iloc[0:2336]
y_train = y.iloc[0:2336]

x_test = scaled_df.iloc[2336:2920]
y_test = y.iloc[2336:2920]

# ------------------------------
# TRAIN MODEL
# ------------------------------
model = GradientBoostingRegressor(
    n_estimators=100,
    learning_rate=0.1,
    max_depth=3,
    random_state=42
)

model.fit(x_train, y_train)

# Save trained model
with open('gradient_boosting_model.pkl', 'wb') as f:
    pickle.dump(model, f)

print("Model and scaler saved successfully!")


import streamlit as st
import pickle
import pandas as pd

# --------------------------------------------------------
# LOAD MODEL & SCALER
# --------------------------------------------------------
@st.cache_resource
def load_artifacts():
    # Load trained model
    with open("gradient_boosting_model.pkl", "rb") as f:
        model = pickle.load(f)

    # Load scaler
    with open("scaler.pkl", "rb") as f:
        scaler = pickle.load(f)

    return model, scaler

model, scaler = load_artifacts()

means = scaler["means"]
stds = scaler["stds"]
feature_order = scaler["feature_order"]

# --------------------------------------------------------
# STREAMLIT UI
# --------------------------------------------------------
st.set_page_config(page_title="Solar Power Prediction App", layout="wide")
st.title("⚡ Solar Power Generation Prediction App")

st.subheader("Enter Feature Inputs")

# CREATES USER INPUT BOXES
def user_input_features():
    inputs = {}
    for feature in feature_order:
        inputs[feature] = st.number_input(
            feature.replace("-", " ").title(),
            value=float(means[feature])  # default = mean
        )
    return pd.DataFrame([inputs])

user_df = user_input_features()

st.write("### Raw Input Data")
st.dataframe(user_df)

# --------------------------------------------------------
# APPLY SAME SCALING AS TRAINING
# --------------------------------------------------------
def scale_input(df):
    scaled = df.copy()
    for col in df.columns:
        scaled[col] = (df[col] - means[col]) / stds[col]
    return scaled

scaled_user_df = scale_input(user_df)

st.write("### Scaled Input Data")
st.dataframe(scaled_user_df)

# --------------------------------------------------------
# PREDICT
# --------------------------------------------------------
if st.button("Predict Power Generation"):
    # Ensure columns are in correct order
    scaled_user_df = scaled_user_df[feature_order]

    prediction = model.predict(scaled_user_df)[0]
    st.success(f"🌞 **Predicted Power Generated:** {prediction:.2f} kW")