# -*- coding: utf-8 -*-
"""Portfolio App.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yipDkuriksQi5PGzQCUZJICs_4zT1xEb
"""

import streamlit as st
from streamlit_lottie import st_lottie
import requests
from PIL import Image

# ---------------------------
# Page Setup
# ---------------------------
st.set_page_config(
    page_title="Data Scientist Portfolio | Your Name",
    page_icon="📊",
    layout="wide"
)

# ---------------------------
# Load Lottie Animations
# ---------------------------
def load_lottie(url: str):
    r = requests.get(url)
    if r.status_code != 200:
        return None
    return r.json()

lottie_welcome = load_lottie("https://lottie.host/363c8b52-70dd-448a-b00a-7b8ce6f666f6/ZhCEHGvV1T.json")
lottie_projects = load_lottie("https://lottie.host/09b42fa3-bf46-45ab-a6fb-45c45b0d53b5/7Yza2O0SbS.json")
lottie_contact = load_lottie("https://lottie.host/7bb1e247-36df-45cc-b506-3fbad2158f31/7NYsBcnUqZ.json")

# ---------------------------
# Load Assets
# ---------------------------
profile_img = Image.open("assets/profile.jpg")
with open("assets/resume.pdf", "rb") as pdf_file:
    PDFbyte = pdf_file.read()

# ---------------------------
# HEADER SECTION
# ---------------------------
col1, col2 = st.columns([1, 2])

with col1:
    st.image(profile_img, width=230)

with col2:
    st.title("👋 Hello, I'm **Your Name**")
    st.subheader("Data Scientist | Business Analyst | Machine Learning Enthusiast")
    st.write("""
    I am a Data Science professional with an MBA background,
    combining business understanding with advanced analytics, ML models and automation.
    """)

    # Resume Download Button
    st.download_button(
        label="📄 Download Resume",
        data=PDFbyte,
        file_name="YourName_Resume.pdf",
        mime="application/pdf",
    )

st.write("---")

# ---------------------------
# ABOUT + ANIMATION
# ---------------------------
col3, col4 = st.columns([2, 1])

with col3:
    st.header("🔍 About Me")
    st.write("""
    With experience in MIS and Data Science, I specialize in:
    - Predictive Modeling
    - Exploratory Data Analysis
    - Business Intelligence
    - Power BI & Dashboarding
    - Machine Learning & Statistical Analysis
    - Automations using Python
    """)
    st.write("I help companies solve business problems using data-driven decisions.")

with col4:
    st_lottie(lottie_welcome, height=250)

st.write("---")

# ---------------------------
# PROJECTS SECTION
# ---------------------------
st.header("📂 Featured Projects")
st.write("Here are some of my best Machine Learning & Analytics projects:")

projects = [
    {
        "title": "🏥 Medical Cost Prediction",
        "desc": "Regression ML model built using XGBoost + Feature Engineering.",
        "github": "https://github.com/",
        "app": "https://yourapp1.streamlit.app/"
    },
    {
        "title": "📈 Stock Forecasting (LSTM)",
        "desc": "Deep Learning model using LSTM to predict future stock prices.",
        "github": "https://github.com/",
        "app": "https://yourapp2.streamlit.app/"
    },
    {
        "title": "🤖 Churn Prediction",
        "desc": "Classification model with SHAP explainability.",
        "github": "https://github.com/",
        "app": "https://yourapp3.streamlit.app/"
    },
    {
        "title": "📊 Sales Dashboard (Power BI)",
        "desc": "Interactive BI dashboard providing business insights.",
        "github": "https://github.com/",
        "app": None
    }
]

for project in projects:
    p1, p2 = st.columns([1, 3])
    with p1:
        st_lottie(lottie_projects, height=130)
    with p2:
        st.subheader(project['title'])
        st.write(project['desc'])
        link1, link2 = st.columns(2)

        with link1:
            st.markdown(f"[💻 GitHub Repo]({project['github']})")
        if project['app']:
            with link2:
                st.markdown(f"[🚀 Live App]({project['app']})")

    st.write("---")

# ---------------------------
# CONTACT SECTION
# ---------------------------
st.header("📮 Contact Me")
col5, col6 = st.columns([2, 1])

with col5:
    with st.form("contact_form"):
        name = st.text_input("Your Name")
        email = st.text_input("Your Email")
        msg = st.text_area("Message")
        submitted = st.form_submit_button("Send Message")

        if submitted:
            st.success("✅ Your message has been sent! I will reply shortly.")

with col6:
    st_lottie(lottie_contact, height=220)

st.write("---")

st.caption("© 2025 Your Name | Data Scientist Portfolio | Powered by Streamlit")